FROM node:alpine as builder

WORKDIR /app
COPY ./app/package*.json ./
RUN npm install
COPY ./settings/.env.production ./
COPY ./app ./
RUN npm run build

FROM nginx
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./settings/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]